In [52]:
import pandas as pd

In [53]:
import spacy
from spacy import displacy

nlp = spacy.load('en_core_web_sm')

In [54]:
ruler = nlp.add_pipe("entity_ruler", config={"validate": True})
patterns = [
    {"label": "PROG", "pattern": "Mathematics", "id": "math"},
    {"label": "PROG", "pattern": "Computer Science", "id": "cpsc"},
    {"label": "PROG", "pattern": "Applied Mathematics", "id": "math"},
]
ruler.add_patterns(patterns)

C:\Users\cloud\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\pipeline\entityruler.py:315: UserWarning: [W012] A Doc object you're adding to the PhraseMatcher for pattern 'PROG||math' is parsed and/or tagged, but to match on 'ORTH', you don't actually need this information. This means that creating the patterns is potentially much slower, because all pipeline components are applied. To only create tokenized Doc objects, try using `nlp.make_doc(text)` or process all texts as a stream using `list(nlp.tokenizer.pipe(all_texts))`.
  self.phrase_matcher.add(label, [pattern])
C:\Users\cloud\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\pipeline\entityruler.py:315: UserWarning: [W012] A Doc object you're adding to the PhraseMatcher for pattern 'PROG||cpsc' is parsed and/or tagged, but to match on 'ORTH', you don't actually need this information. This means that creating the patterns is potentially much slower, because all pipeline components are applied. To only create tokenized Doc objects, try using `nlp.make_doc(text)` or process all texts as a stream using `list(nlp.tokenizer.pipe(all_texts))`.
  self.phrase_matcher.add(label, [pattern])

In [55]:
prereq = "Computer Science 319 or 331; and Mathematics 211 or 213; and 3 units from Mathematics 253, 267, 277, 283 or Applied Mathematics 219."
doc = nlp(prereq)

In [60]:
data = []
for token in doc:
    data.append([token.text, token.lemma_, token.pos_, spacy.explain(token.pos_), token.tag_, token.dep_, token.shape_, token.is_alpha, token.is_stop])

pd.DataFrame(data, columns=["Text", "Lemma", "POS", "Explain", "Tag", "Dependent", "Shape", "Alpha", "Stop word"])

,Text,Lemma,POS,Explain,Tag,Dependent,Shape,Alpha,Stop word
0,Computer,Computer,PROPN,proper noun,NNP,compound,Xxxxx,True,False
1,Science,Science,PROPN,proper noun,NNP,ROOT,Xxxxx,True,False
2,319,319,NUM,numeral,CD,nummod,ddd,False,False
3,or,or,CCONJ,coordinating conjunction,CC,cc,xx,True,True
4,331,331,NUM,numeral,CD,conj,ddd,False,False
5,;,;,PUNCT,punctuation,:,punct,;,False,False
6,and,and,CCONJ,coordinating conjunction,CC,cc,xxx,True,True
7,Mathematics,Mathematics,PROPN,proper noun,NNP,conj,Xxxxx,True,False
8,211,211,NUM,numeral,CD,nummod,ddd,False,False
9,or,or,CCONJ,coordinating conjunction,CC,cc,xx,True,True
10,213,213,NUM,numeral,CD,conj,ddd,False,False
11,;,;,PUNCT,punctuation,:,punct,;,False,False
12,and,and,CCONJ,coordinating conjunction,CC,cc,xxx,True,True
13,3,3,NUM,numeral,CD,nummod,d,False,False
14,units,unit,NOUN,noun,NNS,conj,xxxx,True,False
15,from,from,ADP,adposition,IN,prep,xxxx,True,True
16,Mathematics,Mathematics,PROPN,proper noun,NNP,pobj,Xxxxx,True,False
17,253,253,NUM,numeral,CD,nummod,ddd,False,False
18,",",",",PUNCT,punctuation,",",punct,",",False,False
19,267,267,NUM,numeral,CD,nummod,ddd,False,False
20,",",",",PUNCT,punctuation,",",punct,",",False,False
21,277,277,NUM,numeral,CD,nummod,ddd,False,False
22,",",",",PUNCT,punctuation,",",punct,",",False,False
23,283,283,NUM,numeral,CD,nummod,ddd,False,False
24,or,or,CCONJ,coordinating conjunction,CC,cc,xx,True,True
25,Applied,Applied,PROPN,proper noun,NNP,compound,Xxxxx,True,False
26,Mathematics,Mathematics,PROPN,proper noun,NNP,conj,Xxxxx,True,False
27,219,219,NUM,numeral,CD,nummod,ddd,False,False
28,.,.,PUNCT,punctuation,.,punct,.,False,False

In [57]:
options = {"compact": True}
displacy.render(doc, style="dep", options=options)

In [58]:
displacy.render(doc, style="ent", options=options)

In [59]:
data = [(ent.text, ent.label_) for ent in doc.ents]
pd.DataFrame(data, columns=["Text", "Label"])

                   Text     Label
0      Computer Science      PROG
1                   319  CARDINAL
2                   331  CARDINAL
3           Mathematics      NORP
4                   211  CARDINAL
5                   213  CARDINAL
6                     3  CARDINAL
7       Mathematics 253       LAW
8                   267  CARDINAL
9                   277  CARDINAL
10                  283  CARDINAL
11  Applied Mathematics       ORG